application: ile2015-988
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /bootstrap
  static_dir: bootstrap

# Handler for front page
- url: /
  script: ile2015-988.app

#Handler for view
- url: /view
  script: ile2015-988.app
  
#Handler for search files
- url: /getfiles
  script: ile2015-988.app
  
#Handler for shoutbox
- url: /getchats
  script: ile2015-988.app
  
# All other pages
- url: /.*
  script: ile2015-988.app
  login: required
  
libraries:
- name: jinja2
  version: latest